### ISSUE TITLE
[Feature Request] Ability for a content user to author site navigation that links to Algolia Hierarchical Categories

### ISSUE THREAD

**Issue by jaydubb12** [contentful-labs/contentful-algolia-integration#1]
**Story**
As a content author I should be able to query active Algolia's Hierarchical Category Listings from Contentful for the purpose of authoring content as well as page navigation items in the header

**Use Cases**
A Content Author accesses the site navigation content fragment associated with the SITE HEADER NAV, queries Algolia's Hierarchical Category Listings, and links the navigation text to the Algolia Query .

A Content Author accesses the site navigation content fragment associated with the MOBILE HEADER NAV, queries Algolia's Hierarchical Category Listings, and links the navigation to return the Algolia Query 

A Content Author accesses the site navigation content fragment associated with the SITE FOOTER NAV queries Algolia's Hierarchical Category Listings, and links the navigation text to the Algolia Query 

A Content Author accesses the site navigation content fragment associated with PAGE NAVIGATION CONTENT queries Algolia's Hierarchical Category Listings, and links the navigation text to the Algolia Query 

**Current State**
The current Contentful App connects to Algoia via a Webhook as a means to record content entries into a content index.

**Contentful --> Algolia App Documentation**
https://www.contentful.com/marketplace/webhook/algolia/

**Similar App**
The following app has a read capability and enables a user to read items from a remote system, Shopify in this case, and leverage them as an incremental means of enriching / enabling features to support authoring
[https://www.contentful.com/marketplace/category/search/](https://www.contentful.com/help/shopify-app/)

**Comment by cachrisman** [comment]
Closing as this repo isn't actively maintained
